name: steak

services:

  postgres:
    image: postgres:17.5-alpine3.22
    container_name: pre-event-postgres
    restart: always
    environment:
      POSTGRES_USER: bravos
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: steakdb
    networks:
      - pre-event-networks
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

  redis:
    image: redis:8.0.2-alpine3.21
    container_name: pre-event-redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["redis-server","--requirepass","${REDIS_PASSWORD}"]
    networks:
      - pre-event-networks
    restart: always

  mongo:
    image: mongo:8.0.10-noble
    container_name: pre-event-mongodb
    ports:
      - "27017:27017"
    networks:
      - pre-event-networks
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    restart: always

networks:
  pre-event-networks:
    driver: bridge
