INSERT INTO genre (name, description, slug)
VALUES
    ('Action', 'Fast-paced and exciting, often featuring physical feats and stunts.', 'action'),
    ('Adventure', 'Exploration and discovery, often in exotic locations with puzzles and challenges to solve.', 'adventure'),
    ('RPG', 'Role-playing games where players take on the roles of characters in a fictional setting, influencing the story through choices.', 'rpg'),
    ('Simulation', 'Games that mimic real-life activities such as farming, building, or managing systems like cities or businesses.', 'simulation'),
    ('Strategy', 'Focuses on planning and tactical thinking to achieve victory, whether in combat or resource management.', 'strategy'),
    ('Puzzle', 'Games that challenge players’ problem-solving and critical thinking skills through puzzles or brainteasers.', 'puzzle'),
    ('Sports', 'Games that simulate real-world sports such as football, basketball, racing, or other athletic activities.', 'sports'),
    ('Fighting', 'Competitive games where players control characters in close combat or martial arts battles.', 'fighting'),
    ('Survival', 'Games where players must survive in a hostile environment, gathering resources and defending against threats.', 'survival'),
    ('MMO', 'Massively multiplayer online games that involve large-scale interaction with many players in an ongoing world.', 'mmo'),
    ('Battle Royale', 'A survival game where players fight against each other until only one remains, often on a shrinking map.', 'battle-royale'),
    ('Horror', 'Games designed to evoke fear, often through tense atmosphere and jump scares or creepy storytelling.', 'horror'),
    ('Platformer', 'Games that involve navigating levels by jumping and running, often with obstacles or enemies to avoid.', 'platformer'),
    ('Racing', 'Games centered around racing vehicles, from cars to bikes, in competitive environments.', 'racing'),
    ('Farming', 'Games focused on managing a farm, growing crops, raising animals, and expanding your farm operations.', 'farming'),
    ('Stealth', 'Games that require players to avoid detection by enemies, often through careful planning and strategy.', 'stealth'),
    ('Hack and Slash', 'Action games where the primary focus is on combat, often featuring high-intensity battles with numerous enemies.', 'hack-and-slash'),
    ('Open World', 'Games set in a large, open environment where players can roam freely, engage in side missions, and explore.', 'open-world'),
    ('Sandbox', 'Games where players have creative freedom to interact with the environment and create or modify elements of the game world.', 'sandbox'),
    ('Visual Novel', 'Interactive story-driven games that focus on narrative and character interaction, often with branching storylines.', 'visual-novel'),
    ('Music', 'Games where rhythm and music play a key role, often involving timing and synchronization with beats.', 'music');

INSERT INTO genre (name, description, slug)
VALUES
    ('MMORPG', 'Massively Multiplayer Online Role-Playing Games, where players interact in a persistent world with many others.', 'mmorpg'),
    ('Roguelike', 'Games featuring procedurally generated levels, permanent death, and randomization to create a new experience each playthrough.', 'roguelike'),
    ('Roguelite', 'Similar to Roguelikes but with some permanent progression or power-ups that persist across playthroughs.', 'roguelite'),
    ('Idle', 'Games where the primary progression occurs even when the player is not actively interacting, typically with incremental growth.', 'idle'),
    ('Card Game', 'Games based around card play, where strategy and deck-building are crucial to victory.', 'card-game'),
    ('Trivia', 'Games that test players’ knowledge in various categories through multiple-choice questions or challenges.', 'trivia'),
    ('Tower Defense', 'A strategy game where players must prevent enemies from reaching a certain point by placing defensive structures.', 'tower-defense'),
    ('Hackers', 'Games where players engage in hacking simulations, solving puzzles and gaining access to secure systems.', 'hackers'),
    ('F2P (Free to Play)', 'Games that are free to play but may offer in-game purchases or ads for monetization.', 'f2p'),
    ('VR (Virtual Reality)', 'Games designed to be played in a virtual reality environment, requiring specialized VR equipment.', 'vr'),
    ('AR (Augmented Reality)', 'Games that use augmented reality to blend the virtual and real world, often with mobile devices.', 'ar'),
    ('MOBAs', 'Multiplayer Online Battle Arenas, where players control a single character and work with teammates to destroy the enemy base.', 'moba'),
    ('Survival Horror', 'A subgenre combining survival mechanics and horror, where players must manage resources while evading monsters and threats.', 'survival-horror'),
    ('Shmup (Shoot ’em up)', 'Games that emphasize fast-paced action where players control a ship or character shooting enemies.', 'shmup'),
    ('Metroidvania', 'Action-adventure games with an interconnected world and a focus on exploration and acquiring abilities to access new areas.', 'metroidvania'),
    ('Pick-up-and-play', 'Casual games designed for short, easy-to-learn play sessions, perfect for quick entertainment.', 'pickup-and-play'),
    ('Escape Room', 'Puzzle-based games that challenge players to solve puzzles and riddles to "escape" from a locked environment.', 'escape-room'),
    ('Beat ’em up', 'Action games where players fight large numbers of enemies, typically in side-scrolling stages.', 'beat-em-up'),
    ('Text Adventure', 'Games based on text input, where players explore the story and solve puzzles through written commands.', 'text-adventure'),
    ('Board Game', 'Digital versions of classic board games, or games inspired by traditional tabletop games.', 'board-game'),
    ('Sexual Content', 'Games that include adult themes or explicit content, often with mature storytelling or visuals.', 'sexual-content'),
    ('Educational', 'Games designed to teach or educate players on various subjects through interactive gameplay.', 'educational'),
    ('Dating Sim', 'Simulation games focused on romantic relationships, where players interact with characters to build relationships.', 'dating-sim'),
    ('Interactive Fiction', 'Narrative-driven games that allow players to make choices that affect the story outcome, often with minimal gameplay mechanics.', 'interactive-fiction');

INSERT INTO tag (name, description, slug)
VALUES
    ('Multiplayer', 'Games that allow multiple players to play simultaneously, either cooperatively or competitively.', 'multiplayer'),
    ('Singleplayer', 'Games designed for a single player to experience the game alone.', 'singleplayer'),
    ('Co-op', 'Games designed for players to work together as a team to complete objectives.', 'co-op'),
    ('Online', 'Games that require an internet connection for gameplay and often feature online interaction.', 'online'),
    ('Local', 'Games that can be played on the same device or network, without the need for an internet connection.', 'local'),
    ('Action-packed', 'Games that focus on fast-paced, high-intensity action with frequent combat or challenges.', 'action-packed'),
    ('Story-driven', 'Games with a strong emphasis on narrative and character development, often with branching paths or plot choices.', 'story-driven'),
    ('Fantasy Setting', 'Games set in a magical or fantastical world with mythical creatures, magic, and epic quests.', 'fantasy-setting'),
    ('Sci-Fi', 'Games set in futuristic or science fiction-themed settings, involving advanced technology, space travel, or alien species.', 'sci-fi'),
    ('Post-apocalyptic', 'Games that take place after a catastrophic event, often in a world where survival is the key objective.', 'post-apocalyptic'),
    ('Casual', 'Games that are easy to pick up and play, with simple mechanics and less time investment needed.', 'casual'),
    ('Hardcore', 'Games that require high skill levels and time commitment, often designed for experienced or dedicated players.', 'hardcore'),
    ('Indie', 'Games developed by smaller studios or individual developers, often with unique gameplay mechanics or artistic styles.', 'indie'),
    ('Free-to-play', 'Games that are free to download and play, but may include in-game purchases or ads.', 'free-to-play'),
    ('Paid', 'Games that require a purchase or subscription to play, often with additional content unlocked after the initial buy.', 'paid'),
    ('Early Access', 'Games that are available for purchase before they are fully finished, allowing players to participate in development.', 'early-access'),
    ('Demo', 'A free, limited version of a game that provides a preview of the full experience.', 'demo'),
    ('RPG Elements', 'Games that include elements of role-playing games such as character customization, leveling, and quests.', 'rpg-elements'),
    ('Puzzle-solving', 'Games that focus on solving puzzles, logic challenges, or brainteasers to progress.', 'puzzle-solving'),
    ('Action RPG', 'Games that combine action-based combat with RPG mechanics such as leveling up and questing.', 'action-rpg'),
    ('Multiverse', 'Games that involve multiple universes, dimensions, or alternate realities.', 'multiverse'),
    ('Competitive', 'Games that focus on player-versus-player competition, often in tournaments or ranked systems.', 'competitive'),
    ('Relaxing', 'Games designed to be calming and stress-free, often with soothing visuals and gameplay.', 'relaxing'),
    ('Horror Survival', 'Games that combine horror elements with survival mechanics, where players must avoid or fight monsters.', 'horror-survival'),
    ('Experimental', 'Games that push the boundaries of traditional gaming, often involving unique gameplay mechanics or narratives.', 'experimental');

