openapi: 3.1.0
info:
  title: Steak Publisher API Documentation
  description: Steak Publisher API Documentation
  version: 1.0.0
servers:
  - url: 'http://localhost:8888/'
  - url: 'https://api.steak.io.vn/'
paths:
  /api/v1/dev/auth/register:
    post:
      summary: Đăng ký tài khoản publisher
      description: Pre Đăng ký tài khoản publisher
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PublisherRegistrationRequest"

      responses:
        200:
          description: Oke rồi check mail thôi
        409:
          description: Conflict
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Lỗi khác
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  
components:
  schemas:
    Error:
      description: Lỗi trả về
      type: object
      properties:
        title:
          type: string
          example: "Bad Request"
        status:
          type: integer
          example: 400
        detail:
          type: string
          example: "Sai cú pháp, hay sai cái gì đó"
        instance:
          type: string
          example: "/api/v1/auth/username-login"
        type:
          type: string
          example: "about:blank"

    PublisherRegistrationRequest:
      description: Request
      type: object
      properties:
        name:
          type: string
          example: "Publisher name"
        businessEmail:
          type: string
          example: "bravos@steak.io.vn"
        phone:
          type: string
          example: +84933333333
        masterUsername:
          type: string
          example: steakadmin
        masterEmail:
          type: string
          example: steak@gmail.com
        masterPassword:
          type: string
          example: 0210201@vIP

