openapi: 3.1.0
info:
  title: Steak UserAccount API Documentation
  description: Steak UserAccount API Documentation
  version: 1.0.0
servers:
  - url: 'http://localhost:8888/'
  - url: 'https://api.steak.io.vn/'
paths:
  /api/v1/user/auth/username-login:
    post:
      summary: Đăng nhập username
      description: Đăng nhập bằng username
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UsernameLoginRequest"
      responses:
        200:
          description: Đăng nhập, lấy token và accessToken
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        400:
          description: Sai cú pháp, hay sai cái gì đó
        401:
          description: Sai tài khoản mật khẩu
        403:
          description: Tài khoản bị khóa

  /api/v1/user/auth/email-login:
    post:
      summary: Đăng nhập email
      description: Đăng nhập bằng email
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmailLoginRequest"
      responses:
        200:
          description: Đăng nhập, lấy token và accessToken
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        400:
          description: Sai cú pháp, hay sai cái gì đó
        401:
          description: Sai tài khoản mật khẩu
        403:
          description: Tài khoản bị khóa<

  /api/v1/user/auth/register:
    post:
      summary: Đăng ký
      description: Gửi yêu cầu đăng ký tài khoản
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        200:
          description: Tạo lệnh đăng ký thành công, trả về email đăng ký
        409:
          description: Tài khoản đã tồn tại
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Lỗi không xác định
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/v1/user/auth/refresh:
    post:
      summary: Lấy lại token cho user
      description: Lấy lại token bằng refreshToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshRequest"
      responses:
        200:
          description: Lấy lại token thành công
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        default:
          description: Lỗi không xác định
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"


components:
  schemas:
    Error:
      description: Lỗi trả về
      type: object
      properties:
        title:
          type: string
          example: "Bad Request"
        status:
          type: integer
          example: 400
        detail:
          type: string
          example: "Sai cú pháp, hay sai cái gì đó"
        instance:
          type: string
          example: "/api/v1/auth/username-login"
        type:
          type: string
          example: "about:blank"

    UsernameLoginRequest:
      description: Đăng nhập bằng username
      type: object
      properties:
        username:
          type: string
          minLength: 6
          maxLength: 32
          example: bravos123
        password:
          type: password
          example: PassW0rD@
        deviceId:
          type: string
          example: 1q2w3whj4j3nk
        deviceInfo:
          type: string
          example: ubuntu chrome browser
    EmailLoginRequest:
      description: Đăng nhập bằng email
      type: object
      properties:
        email:
          type: email
          minLength: 6
          maxLength: 32
          example: bravos123@baodepzai.com
        password:
          type: password
          example: PassW0rD@
        deviceId:
          type: string
          example: 1q2w3whj4j3nk
        deviceInfo:
          type: string
          example: ubuntu chrome browser
    LoginResponse:
      type: object
      properties:
        name:
          type: string
          example: QuocBaoDepTrai
        avatar:
          type: string
          example: https://ccdn.steak.io.vn
    RegisterRequest:
      type: object
      properties:
        username:
          type: string
          minLength: 6
          maxLength: 32
          example: bravos123
        email:
          type: email
          example: bravos@steak.vn
        password:
          type: password
          example: PassworD2@
    RefreshRequest:
      type: object
      properties:
        deviceId:
          type: string
          example: 1q2w3whj4j3nk

  
