name: CI - Build and Deploy Spring Boot

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build docker image
        run: |
          docker login --username bravos --password ${{ secrets.DOCKER_PASSWORD }}
          docker build -t bravos/steak-server:latest .
          docker push bravos/steak-server:latest

      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.PRIVATE_KEY }}
            port: ${{ secrets.PORT }}
            script: |
              docker login --username bravos --password ${{ secrets.DOCKER_PASSWORD }}
              docker stop steak-server || true
              docker rm steak-server || true
              docker pull bravos/steak-server:latest
              docker run -d -p 8888:8888 --name steak-server -e AZURE_CLIENT_ID -e AZURE_CLIENT_SECRET -e AZURE_TENANT_ID -e KEY_IDENTIFIER -e VAULT_URL -e SPRING_PROFILES_ACTIVE=prod bravos/steak-server:latest
          
